### ISSUE TITLE
Error while deploying chapter 4 code on aws lambda, using same codebase as mentioned in book.

### ISSUE THREAD

**Issue by gaurav386i** [PacktPublishing/Building-Serverless-Python-Web-Services-with-Zappa#3]
Scheduled flask-restapi-dev-zappa-keep-warm-handler.keep_warm_callback with expression rate(4 minutes)!
Uploading flask-restapi-dev-template-1581447250.json (1.6KiB)..
100%|███████████████████████████████| 1.64K/1.64K [00:00<00:00, 12.2KB/s]
Waiting for stack flask-restapi-dev to create (this can take a bit)..
100%|█████████████████████████████████████| 4/4 [00:06<00:00,  2.58s/res]
Deploying API Gateway..
Error: Warning! Status check on the deployed lambda failed. A GET request to '/' yielded a 502 response code.

**Comment by sarvesh-packt** [comment]
Hi gaurav386i,

This issue is because of the mismatch version of pip and Zappa
Kindly refer to https://github.com/Miserlou/Zappa/issues/1536 for this issue's solution.

Regards,
Sarvesh
